[project]
name = "assignment"
version = "0.1.0"
description = "Practical AI - Assignment 01."
license = "MIT"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
]

[tool.uv]
cache-dir = ".uv_cache"

[tool.ruff]
line-length = 79

[tool.ruff.lint]
extend-select = ["I"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]

